query:
  'query {organization(login:"USGS-WiM") {
    id
    name
    repositories($order:100) {
        nodes {
            id
            name
            createdAt
            description
            object(expression: "master:code.json") {
                ... on Blob {
                   text
                }
            }
        }
    }
  }
}'
variables:
  order:
    type: arg
    name: order
