# query:
#   'query {organization(login:"USGS-WiM") {
#     id
#     name
#     repositories(first:100) {
#         nodes {
#             id
#             name
#             createdAt
#             description
#             homepageUrl
#             object(expression: "master:code.json") {
#                 ... on Blob {
#                    text
#                 }
#             }
#         }
#     }
#   }
# }'
