on:
  push:
    branches:
    - staging
name: "Push to test.wim.usgs.gov (TEST)"
jobs:
  pushToTest:
    name: Push to TETST
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set Up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15'
    - run: npm run-script build
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: aws s3 cp /home/runner/work/WIM-Main-Site/WIM-Main-Site/builds/prosduction/ s3://test.wim.usgs.gov/ --recursive

    -name: AWS Test Failure
      if: failure()
      uses: Ilshidur/action-slack@2a8ddb6db23f71a413f9958ae75bbc32bbaa6385
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: ":warning::warning: Error deploying *wim-main-site* to :test:test.wim.usgs.gov - GitHub Action Failed :warning::warning:"

    - name: GitHub Action for Slack
      uses: Ilshidur/action-slack@2a8ddb6db23f71a413f9958ae75bbc32bbaa6385
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: ":test: Successfully deployed TEST to test.wim.usgs.gov :fire:"

