on:
  push:
    branches:
    - staging
name: "Push to test.wim.usgs.gov (TEST)"
jobs:
  pushToTest:
    name: Push to TETST
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set Up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15'
    - run: npm run-script build
      
    - name: GitHub Action for AWS-1
      uses: actions/aws/cli@efb074ae4510f2d12c7801e4461b65bf5e8317e6
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 cp /github/workspace/builds/production/ s3://test.wim.usgs.gov/
          --recursive
    - name: GitHub Action for Slack
      uses: Ilshidur/action-slack@2a8ddb6db23f71a413f9958ae75bbc32bbaa6385
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: "Successfully deployed TEST to test.wim.usgs.gov :fire:"

