on:
  push:
    branches:
    - master
name: Push to Prod Site
jobs:
  pushToProd:
    name: Push to Prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for npm
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: run-script build
    - name: GitHub Action for AWS
      uses: actions/aws/cli@efb074ae4510f2d12c7801e4461b65bf5e8317e6
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 cp /github/workspace/builds/production/ s3://wim.usgs.gov/
          --recursive
    - name: GitHub Action for Slack
      uses: Ilshidur/action-slack@2a8ddb6db23f71a413f9958ae75bbc32bbaa6385
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: Successfully deployed to prod site
