on:
  schedule:
  - cron: '50 20 * * *'
name: Test Repo Workflow
jobs:
  graphQLQuery2:
    name: GraphQL query2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GraphQL query2
      uses: helaili/github-graphql-action@fb0ce78d56777b082e1a1659faf2b9f5a8832ed3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --query .github/graph-ql.query2.yaml --output repos2.json
    - name: GraphQL query
      uses: helaili/github-graphql-action@fb0ce78d56777b082e1a1659faf2b9f5a8832ed3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --query .github/graph-ql.query.yaml --output repos1.json
    - name: Repos To AWS - Test 1
      uses: actions/aws/cli@efb074ae4510f2d12c7801e4461b65bf5e8317e6
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 cp /github/workspace/repos1.json s3://test.wim.usgs.gov/src/repos1.json
    - name: Repos To AWS - Test 2
      uses: actions/aws/cli@efb074ae4510f2d12c7801e4461b65bf5e8317e6
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 cp /github/workspace/repos2.json s3://test.wim.usgs.gov/src/repos2.json
